/*
 * SPI_cfg.h
 *
 *  Created on: Sep 24, 2022
 *      Author: mostafa_ebrahim
 */

#ifndef MCAL_SPI_SPI_CFG_H_
#define MCAL_SPI_SPI_CFG_H_

/*Configuration of SPI Pins*/

#define SPI_SCK_PORT PORTB_ID
#define SPI_SCK_PIN PIN7_ID

#define SPI_MISO_PORT PORTB_ID
#define SPI_MISO_PIN  PIN6_ID

#define SPI_MOSI_PORT PORTB_ID
#define SPI_MOSI_PIN PIN5_ID

#define SPI_SS_PORT PORTB_ID
#define SPI_SS_PIN PIN4_ID

/*SPI INT Options:
1-SPI_INT_DISABLE
2-SPI_INT_ENABLE
**/
#define SPI_INT_STATE SPI_INT_DISABLE

/*SPI Mode Options:
 * 1-SPI_SLAVE
 * 2-SPI_MASTER
 * */
#define SPI_MODE SPI_SLAVE

/*SPI Data Order Options:
 * 1-SPI_DORD_MSB
 * 2-SPI_DORD_LSB
 * */
#define SPI_DORD_SELECT SPI_DORD_LSB

/*SPI Clock Polarity options:
 * 1-SPI_CLK_POLARITY_LEADING_RISING_TRAILING_FALLING
 * 2-SPI_CLK_POLARITY_LEADING_FALLING_TRAILING_RISING
 * */
#define SPI_CLK_POLARITY_SELECT SPI_CLK_POLARITY_LEADING_RISING_TRAILING_FALLING

/*SPI Clock Phase Options:
 * 1-SPI_CLK_PHASE_LEADING_SAMPLE_TRAILING_SETUP
 * 2-SPI_CLK_PHASE_LEADING_SETUP_TRAILING_SAMPLE
 * */
#define SPI_CLK_PHASE_SELECT SPI_CLK_PHASE_LEADING_SETUP_TRAILING_SAMPLE

/*SPI Prescaler Options:
 * 1-SPI_4_PRESCALER
 * 2-SPI_16_PRESCALER
 * 3-SPI_64_PRESCALER
 * 4-SPI_128_PRESCALER
 */
#define SPI_PRESCALER_SELECT SPI_4_PRESCALER

/*SPI2X Options:
 * 1-SPI2X_DISABLE
 * 2-SPI2X_ENABLE
 * */
#define SPI2X_STATE SPI2X_DISABLE
#endif /* MCAL_SPI_SPI_CFG_H_ */
