/*
 * TIMER_cfg.h
 *
 *  Created on: Sep 13, 2022
 *      Author: mostafa_ebrahim
 */

#ifndef MCAL_TIMER0_TIMER0_CFG_H_
#define MCAL_TIMER0_TIMER0_CFG_H_

/*options of Timer0 Mode:
 * TIMER0_NORMAL_MODE
 * TIMER0_PWM_PHASE_CORRECT_MODE
 * TIMER0_CTC_MODE
 * TIMER0_FAST_PWM_MODE
 * */
#define TIMER0_MODE TIMER0_FAST_PWM_MODE

/*options of TIMER0 Clock Select:
*TIMER0_NO_CLK
*TIMER0_NO_PRESCALER
*TIMER0_8_PRESCALER
*TIMER0_64_PRESCALER
*TIMER0_256_PRESCALER
*TIMER0_1024_PRESCALER
*EXT_CLK_FALLING_EDGE
*EXT_CLK_RISINGING_EDGE
**/
#define TIMER0_CLOCK_SELECT TIMER0_8_PRESCALER

/*OC0 pin option CTC
 * TIMER0_OC0_DISCONNECTED
 * TIMER0_OC0_TOGGLE
 * TIMER0_OC0_CLR
 * TIMER0_OC0_SET
 *
 * */
#define TIMER0_OCP_PIN_MODE TIMER0_OC0_TOGGLE

/* interrupt state
 *
 * Options:
 * 1- TIMER0_INT_ENABLE
 * 2- TIMER0_INT_DISABLE
 * */
#define TIMER0_INTERRUPT_STATE_OVF TIMER0_INT_DISABLE
#define TIMER0_INTERRUPT_STATE_CTC TIMER0_INT_DISABLE


/* TIMER0 FCPU frequency
 *
 *	Options:
 *	user specify the frequency
 * */
#define TIMER0_InputFreq 8000000UL


/*PWM Mode Options:
 * TIMER0_PWM_NON_INVERTING
 * TIMER0_PWM_INVERTING
 * NOTE:
 * NON_INVERTING:Duty Cycle->OCR
 * INVERTING:Duty Cycle ~OCR*/
#define TIMER0_PWM_MODE TIMER0_PWM_NON_INVERTING

/* OC0 Pin Configuration */
#define OC0_PORT PORTB_ID
#define OC0_PIN	 PIN3_ID

#endif /* MCAL_TIMER0_TIMER0_CFG_H_ */
