/*
 * TRUBIDITY_SENSOR_cfg.h
 *
 *  Created on: Oct 20, 2022
 *      Author: hp
 */

#ifndef TRUBIDITY_SENSOR_TRUBIDITY_SENSOR_CFG_H_
#define TRUBIDITY_SENSOR_TRUBIDITY_SENSOR_CFG_H_

/*Turbidity_SENSOR_ADC_CHANNEL Options:
 *1-CHANNEL0
 *2-CHANNEL1
 *3-CHANNEL2
 *4-CHANNEL3
 *5-CHANNEL4
 *6-CHANNEL5
 *7-CHANNEL6
 *8-CHANNEL7
 * */

#define Turbidity_SENSOR_ADC_CHANNEL CHANNEL1

#endif /* TRUBIDITY_SENSOR_TRUBIDITY_SENSOR_CFG_H_ */
